version: '3'

services:
  build:
    image: golang:1.13.8-alpine3.11
    environment: 
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
    volumes:
      - .:/go/src/dns_helper
    stdin_open: true
    tty: true
    working_dir: /go/src/dns_helper